'use client'

import { useState } from 'react'
import { Download, Loader2 } from 'lucide-react'
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

export interface StageBreakdown {
  stage: string
  count: number
}

export interface CounselorReportData {
  counselorId: string
  counselorName: string
  leadsHanded: number
  leadsContacted: number
  filesOpened: number
  leadsCreated: number
  activePipeline: number
  stageBreakdown: StageBreakdown[]
}

interface DownloadPDFButtonProps {
  report: CounselorReportData
  dateRange: string
  filename: string
}

export function DownloadPDFButton({ report, dateRange, filename }: DownloadPDFButtonProps) {
  const [isGenerating, setIsGenerating] = useState(false)

  const handleDownload = () => {
    setIsGenerating(true)

    try {
      const doc = new jsPDF()

      // 1. Header
      doc.setFontSize(22)
      doc.setTextColor(30, 58, 138) // Tailwind blue-900
      doc.text('Counselor Performance Report', 14, 22)

      doc.setFontSize(14)
      doc.setTextColor(55, 65, 81) // Tailwind gray-700
      doc.text(`Counselor: ${report.counselorName}`, 14, 32)
      
      doc.setFontSize(10)
      doc.setTextColor(107, 114, 128) // Tailwind gray-500
      doc.text(`Period: ${dateRange}`, 14, 38)

      doc.setDrawColor(229, 231, 235) // Tailwind gray-200
      doc.line(14, 43, 196, 43)

      // 2. Metrics Summary Table
      doc.setFontSize(14)
      doc.setTextColor(31, 41, 55) // Tailwind gray-800
      doc.text('Key Metrics', 14, 55)

      autoTable(doc, {
        startY: 60,
        head: [['Metric', 'Value']],
        body: [
          ['Leads Handed (Assigned in period)', report.leadsHanded.toString()],
          ['Leads Contacted (First touch in period)', report.leadsContacted.toString()],
          ['Files Opened (Opened in period)', report.filesOpened.toString()],
          ['Leads Created (Generated by counselor)', report.leadsCreated.toString()],
          ['Active Pipeline (Total currently assigned)', report.activePipeline.toString()],
        ],
        theme: 'grid',
        headStyles: { fillColor: [243, 244, 246], textColor: [55, 65, 81] },
        alternateRowStyles: { fillColor: [250, 250, 250] },
      })

      // 3. Stage Breakdown Table
      // @ts-expect-error - jspdf-autotable extends jsPDF with finalY
      const previousY = doc.lastAutoTable.finalY

      doc.setFontSize(14)
      doc.setTextColor(31, 41, 55)
      doc.text('Pipeline Stage Breakdown', 14, previousY + 15)

      const stageBody = [...report.stageBreakdown]
        .sort((a, b) => b.count - a.count)
        .map((s) => [s.stage, s.count.toString()])

      autoTable(doc, {
        startY: previousY + 20,
        head: [['Stage', 'Count']],
        body: stageBody,
        theme: 'grid',
        headStyles: { fillColor: [243, 244, 246], textColor: [55, 65, 81] },
        alternateRowStyles: { fillColor: [250, 250, 250] },
      })

      // 4. Footer
      const pageCount = doc.getNumberOfPages()
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i)
        doc.setFontSize(8)
        doc.setTextColor(156, 163, 175)
        doc.text(
          'Generated by CoachingSync Management System',
          doc.internal.pageSize.getWidth() / 2,
          doc.internal.pageSize.getHeight() - 10,
          { align: 'center' }
        )
      }

      // Save
      doc.save(filename)
    } catch (error) {
      console.error('Failed to generate PDF', error)
    } finally {
      setIsGenerating(false)
    }
  }

  return (
    <button
      onClick={handleDownload}
      disabled={isGenerating}
      className="flex items-center space-x-2 px-3 py-1.5 bg-neutral-800 hover:bg-neutral-700 text-neutral-300 hover:text-white rounded-sm transition-colors border border-neutral-700 disabled:opacity-50 text-sm font-medium"
      title="Download as PDF"
    >
      {isGenerating ? (
        <>
          <Loader2 className="w-4 h-4 animate-spin" />
          <span>Generating PDF...</span>
        </>
      ) : (
        <>
          <Download className="w-4 h-4" />
          <span>Download PDF</span>
        </>
      )}
    </button>
  )
}
